### ISSUE TITLE
Cata Error - ReforgeEngine.lua:453 & ReforgeEngine.lua:899

### ISSUE THREAD

**Issue by evilgodly** [skyler-code/ReforgeLite#22] opened 2024-06-22 20:06 UTC
Got these 2 Errors on my Mage in SW at the Reforger on Cata Classic

Using addons preset Mage Fire 25% Haste:
1x ReforgeLite/ReforgeEngine.lua:453: script ran too long
[string "@ReforgeLite/ReforgeEngine.lua"]:453: in function `?'
[string "@ReforgeLite/ReforgeEngine.lua"]:896: in function <ReforgeLite/ReforgeEngine.lua:885>
[string "=(tail call)"]: ?
[string "@ReforgeLite/ReforgeLite.lua"]:1377: in function <ReforgeLite/ReforgeLite.lua:1376>

Locals:
self = ReforgeLite {
 BottomLeftCorner = Texture {
 }
 itemTable = Frame {
 }
 GetMeleeHitBonus = <function> defined @ReforgeLite/Presets.lua:52
 IsReforgeMatching = <function> defined @ReforgeLite/ReforgeLite.lua:2060
 InitPresets = <function> defined @ReforgeLite/Presets.lua:876
 ParseWoWSimsString = <function> defined @ReforgeLite/ReforgeLite.lua:470
 GetCapScore = <function> defined @ReforgeLite/ReforgeLite.lua:445
 CapAllows = <function> defined @ReforgeLite/ReforgeEngine.lua:220
 ChooseReforgeClassic = <function> defined @ReforgeLite/ReforgeEngine.lua:446
 dbkey = "Magegoddess - Mankrik"
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 ReorderCapPoint = <function> defined @ReforgeLite/ReforgeLite.lua:1019
 UpgradeDB = <function> defined @ReforgeLite/ReforgeLite.lua:142
 methodReset = Button {
 }
 ADDON_LOADED = <function> defined @ReforgeLite/ReforgeLite.lua:2277
 ComputeReforgeCore = <function> defined @ReforgeLite/ReforgeEngine.lua:854
 debugButton = Button {
 }
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 OnTooltipSetItem = <function> defined @ReforgeLite/ReforgeLite.lua:2210
 tankingStats = <table> {
 }
 deletePresetButton = ReforgeLiteDeletePresetButton {
 }
 TopEdge = Texture {
 }
 statWeightsCategory = Frame {
 }
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetNeededMeleeHit = <function> defined @ReforgeLite/Presets.lua:65
 UpdateMethodCategory = <function> defined @ReforgeLite/ReforgeLite.lua:1551
 pawnButton = ReforgeLiteImportPawnButton {
 }
 OnCommand = <function> defined @ReforgeLite/ReforgeLite.lua:2304
 presetMenu = ReforgeLitePresetMenu {
 }
 GetMethodScore = <function> defined @ReforgeLite/ReforgeEngine.lua:46
 targetLevelText = FontString {
 }
 CreateFrame = <function> defined @ReforgeLite/ReforgeLite.lua:728
 SetTankingModel = <function> defined @ReforgeLite/ReforgeLite.lua:1060
 SetAnchor = <function> defined @ReforgeLite/ReforgeLite.lua:621
 IsItemLocked = <function> defined @ReforgeLite/ReforgeEngine.lua:231
 pdb = <table> {
 }
 itemSlots = <table> {
 }
 GetPlayerBuffs = <function> defined @ReforgeLite/ReforgeEngine.lua:12
 statWeights = Frame {
 }
 STATS = <table> {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 ParsePawnString = <function> defined @ReforgeLite/ReforgeLite.lua:497
 UpdateMethodStats = <function> defined @ReforgeLite/ReforgeEngine.lua:140
 methodStats = Frame {
 }
 SetStatWeights = <function> defined @ReforgeLite/ReforgeLite.lua:1068
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 scrollBarShown = true
 InitReforgeTank = <function> defined @ReforgeLite/ReforgeEngine.lua:716
 GetExpertiseBonus = <function> defined @ReforgeLite/Presets.lua:58
 MakeReforgeOption = <function> defined @ReforgeLite/ReforgeEngine.lua:241
 UpdateBuffs = <function> defined @ReforgeLite/ReforgeLite.lua:1199
 settingsCategory = Frame {
 }
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 UpdateContentSize = <function> defined @ReforgeLite/ReforgeLite.lua:1723
 CreateItemStats = <function> defined @ReforgeLite/ReforgeLite.lua:266
 capPresets = <table> {
 }
 close = Button {
 }
 CreateOptionList = <function> defined @ReforgeLite/ReforgeLite.lua:1232
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetReforgeIDFromString = <function> define

Using Addon Presets Mage > 15% Haste
1x ReforgeLite/ReforgeEngine.lua:899: script ran too long
[string "@ReforgeLite/ReforgeEngine.lua"]:899: in function <ReforgeLite/ReforgeEngine.lua:885>
[string "=(tail call)"]: ?
[string "@ReforgeLite/ReforgeLite.lua"]:1377: in function <ReforgeLite/ReforgeLite.lua:1376>

Locals:
self = ReforgeLite {
 BottomLeftCorner = Texture {
 }
 itemTable = Frame {
 }
 GetMeleeHitBonus = <function> defined @ReforgeLite/Presets.lua:52
 IsReforgeMatching = <function> defined @ReforgeLite/ReforgeLite.lua:2060
 InitPresets = <function> defined @ReforgeLite/Presets.lua:876
 ParseWoWSimsString = <function> defined @ReforgeLite/ReforgeLite.lua:470
 GetCapScore = <function> defined @ReforgeLite/ReforgeLite.lua:445
 CapAllows = <function> defined @ReforgeLite/ReforgeEngine.lua:220
 ChooseReforgeClassic = <function> defined @ReforgeLite/ReforgeEngine.lua:446
 dbkey = "Magegoddess - Mankrik"
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 ReorderCapPoint = <function> defined @ReforgeLite/ReforgeLite.lua:1019
 UpgradeDB = <function> defined @ReforgeLite/ReforgeLite.lua:142
 methodReset = Button {
 }
 ADDON_LOADED = <function> defined @ReforgeLite/ReforgeLite.lua:2277
 ComputeReforgeCore = <function> defined @ReforgeLite/ReforgeEngine.lua:854
 debugButton = Button {
 }
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 OnTooltipSetItem = <function> defined @ReforgeLite/ReforgeLite.lua:2210
 tankingStats = <table> {
 }
 deletePresetButton = ReforgeLiteDeletePresetButton {
 }
 TopEdge = Texture {
 }
 statWeightsCategory = Frame {
 }
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetNeededMeleeHit = <function> defined @ReforgeLite/Presets.lua:65
 UpdateMethodCategory = <function> defined @ReforgeLite/ReforgeLite.lua:1551
 pawnButton = ReforgeLiteImportPawnButton {
 }
 OnCommand = <function> defined @ReforgeLite/ReforgeLite.lua:2304
 presetMenu = ReforgeLitePresetMenu {
 }
 GetMethodScore = <function> defined @ReforgeLite/ReforgeEngine.lua:46
 targetLevelText = FontString {
 }
 CreateFrame = <function> defined @ReforgeLite/ReforgeLite.lua:728
 SetTankingModel = <function> defined @ReforgeLite/ReforgeLite.lua:1060
 SetAnchor = <function> defined @ReforgeLite/ReforgeLite.lua:621
 IsItemLocked = <function> defined @ReforgeLite/ReforgeEngine.lua:231
 pdb = <table> {
 }
 itemSlots = <table> {
 }
 GetPlayerBuffs = <function> defined @ReforgeLite/ReforgeEngine.lua:12
 statWeights = Frame {
 }
 STATS = <table> {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 ParsePawnString = <function> defined @ReforgeLite/ReforgeLite.lua:497
 UpdateMethodStats = <function> defined @ReforgeLite/ReforgeEngine.lua:140
 methodStats = Frame {
 }
 SetStatWeights = <function> defined @ReforgeLite/ReforgeLite.lua:1068
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 scrollBarShown = true
 InitReforgeTank = <function> defined @ReforgeLite/ReforgeEngine.lua:716
 GetExpertiseBonus = <function> defined @ReforgeLite/Presets.lua:58
 MakeReforgeOption = <function> defined @ReforgeLite/ReforgeEngine.lua:241
 UpdateBuffs = <function> defined @ReforgeLite/ReforgeLite.lua:1199
 settingsCategory = Frame {
 }
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 UpdateContentSize = <function> defined @ReforgeLite/ReforgeLite.lua:1723
 CreateItemStats = <function> defined @ReforgeLite/ReforgeLite.lua:266
 capPresets = <table> {
 }
 close = Button {
 }
 CreateOptionList = <function> defined @ReforgeLite/ReforgeLite.lua:1232
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetReforgeIDFromString = <function> define

**Comment by skyler-code** [comment] 2024-07-20 08:00
Duplicate of #7

**Closed by skyler-code** 2024-07-20 08:00 UTC
