### ISSUE TITLE
Cata Prot Paladin Reforging Error

### ISSUE THREAD

**Issue by dtsaryov** [skyler-code/ReforgeLite#27] opened 2024-07-18 21:25 UTC
```
Date: 2024-07-18 23:21:20
ID: 2
Error occured in: Global
Count: 1
Message: Interface/AddOns/ReforgeLite/Presets.lua line 10:
   script ran too long
Debug:
   [string "@Interface/AddOns/ReforgeLite/Presets.lua"]:10: RatingPerPoint()
   [string "@Interface/AddOns/ReforgeLite/ReforgeEngine.lua"]:46: DiminishStat()
   [string "@Interface/AddOns/ReforgeLite/ReforgeEngine.lua"]:748: ?()
   [string "@Interface/AddOns/ReforgeLite/ReforgeEngine.lua"]:834:
      Interface/AddOns/ReforgeLite/ReforgeEngine.lua:824
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:1440:
      Interface/AddOns/ReforgeLite/ReforgeLite.lua:1439
Locals:
self = ReforgeLite {
 0 = <userdata>
 itemTable = Frame {
 }
 GetMeleeHitBonus = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:53
 IsReforgeMatching = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2144
 InitPresets = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:833
 ParseWoWSimsString = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:486
 GetCapScore = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:461
 CapAllows = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:222
 ChooseReforgeClassic = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:399
 dbkey = "Газпалас - Пламегор"
 ClearBackdrop = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:282
 ParseImportString = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:513
 ReorderCapPoint = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1056
 UpgradeDB = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:150
 methodReset = Button {
 }
 ADDON_LOADED = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2378
 ComputeReforgeCore = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:793
 debugButton = Button {
 }
 HasBackdropInfo = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:278
 OnTooltipSetItem = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2294
 tankingStats = <table> {
 }
 deletePresetButton = ReforgeLiteDeletePresetButton {
 }
 TopEdge = Texture {
 }
 statWeightsCategory = Frame {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetNeededMeleeHit = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:66
 UpdateMethodCategory = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1624
 pawnButton = ReforgeLiteImportPawnButton {
 }
 OnCommand = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2373
 presetMenu = ReforgeLitePresetMenu {
 }
 GetMethodScore = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:48
 targetLevelText = FontString {
 }
 CreateFrame = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:760
 SetTankingModel = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1097
 SetAnchor = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:651
 IsItemLocked = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:233
 pdb = <table> {
 }
 itemSlots = <table> {
 }
 GetPlayerBuffs = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:14
 statWeights = Frame {
 }
 STATS = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:266
 ParsePawnString = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:532
 UpdateMethodStats = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:142
 methodStats = Frame {
 }
 SetStatWeights = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1105
 SwapFrameLevels = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:747
 autoOpened = true
 RemoveCapPoint = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1044
 GetExpertiseBonus = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:59
 MakeReforgeOption = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:241
 UpdateBuffs = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1241
 initialized = true
 settingsCategory = Frame {
 }
 SetupPieceVisuals = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:246
 UpdateContentSize = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1796
 methodTank = Frame {
 }
 scrollBar = ReforgeLiteScrollBar {
 }
 CreateItemStats = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:281
 InitCustomPresets = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:822
 capPresets = <table> {
 }
 close
AddOns:
  Swatter, v4.4.6991 (SwimmingSeadragon)
  Ace3, vRelease-r1341
  AtlasLootClassic, vv4.0.1-beta1
  AtlasLootClassicData, vv4.0.1-beta1
  AtlasLootClassicDungeonsAndRaids, vv4.0.1-beta1
  Auctionator, v10.2.54
  BagBrother, v
  Bagnon, v10.2.31
  BeanCounter, v4.4.6991 (SwimmingSeadragon)
  Bistooltip, v8.09
  DBMCore, v10.2.54
  DBMStatusBarTimers, v10.2.54
  DBMVPVEM, veeae112
  Details, v#Details.12813.158
  DetailsTinyThreat, v
  ElvUI, vv13.70
  ElvUILibraries, vv13.70
  Informant, v4.4.6991 (SwimmingSeadragon)
  ItemRack, v4.00
  LeatrixMaps, v4.0.16
  MinimapButtonButton, v1.18.1
  NovaInstanceTracker, v1.68
  Pawn, v2.9.13
  Questie, v10.3.6
  ReforgeLite, vv1.7.2
  Stubby, v4.4.6991 (SwimmingSeadragon)
  WeakAuras, v5.15.0
  WeakAurasArchive, v5.15.0
  WowSimsExporter, vv2.11.4
  BlizRuntimeLib v4.4.0.55639(EU) <ruRU>
  (ck=347)
```

**Comment by dtsaryov** [comment] 2024-07-18 21:27
Fixed after changing speed

**Comment by skyler-code** [comment] 2024-07-20 08:01
Duplicate of #7

**Closed by skyler-code** 2024-07-20 08:01 UTC
