### ISSUE TITLE
Stump of Time - Script Takes Too Long

### ISSUE THREAD

**Issue by sollisk** [skyler-code/ReforgeLite#19] opened 2024-06-19 01:12 UTC
When calculating a reforge without Stump of Time equipped the calculations occur quite quickly and succeed, but when running calculations as soon as Stump of Time is equipped I get the following error:
```
Message: Interface/AddOns/ReforgeLite/ReforgeEngine.lua:899: script ran too long
Time: Tue Jun 18 20:11:06 2024
Count: 2
Stack: Interface/AddOns/ReforgeLite/ReforgeEngine.lua:899: script ran too long
[string "@Interface/AddOns/ReforgeLite/ReforgeEngine.lua"]:899: in function <Interface/AddOns/ReforgeLite/ReforgeEngine.lua:885>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:1375: in function <Interface/AddOns/ReforgeLite/ReforgeLite.lua:1374>

Locals: self = ReforgeLite {
 BottomLeftCorner = Texture {
 }
 itemTable = Frame {
 }
 GetMeleeHitBonus = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:52
 IsReforgeMatching = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2058
 InitPresets = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:876
 ParseWoWSimsString = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:470
 GetCapScore = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:445
 CapAllows = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:220
 ChooseReforgeClassic = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:446
 dbkey = "Example - Old Blanchy"
 ClearBackdrop = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:282
 ReorderCapPoint = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1019
 UpgradeDB = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:142
 methodReset = Button {
 }
 ADDON_LOADED = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2275
 ComputeReforgeCore = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:854
 debugButton = Button {
 }
 HasBackdropInfo = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:278
 OnTooltipSetItem = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2208
 tankingStats = <table> {
 }
 deletePresetButton = ReforgeLiteDeletePresetButton {
 }
 TopEdge = Texture {
 }
 statWeightsCategory = Frame {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetNeededMeleeHit = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:65
 UpdateMethodCategory = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1549
 pawnButton = ReforgeLiteImportPawnButton {
 }
 OnCommand = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:2302
 presetMenu = ReforgeLitePresetMenu {
 }
 GetMethodScore = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:46
 targetLevelText = FontString {
 }
 CreateFrame = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:728
 SetTankingModel = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1060
 SetAnchor = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:621
 IsItemLocked = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:231
 pdb = <table> {
 }
 itemSlots = <table> {
 }
 GetPlayerBuffs = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:12
 statWeights = Frame {
 }
 STATS = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:266
 ParsePawnString = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:497
 UpdateMethodStats = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:140
 methodStats = Frame {
 }
 SetStatWeights = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1068
 OnBackdropSizeChanged = <function> defined @Interface/AddOns/Blizzard_SharedXML/Backdrop.lua:182
 scrollBarShown = true
 InitReforgeTank = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:716
 GetExpertiseBonus = <function> defined @Interface/AddOns/ReforgeLite/Presets.lua:58
 MakeReforgeOption = <function> defined @Interface/AddOns/ReforgeLite/ReforgeEngine.lua:241
 UpdateBuffs = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:
```

**Comment by skyler-code** [comment] 2024-07-20 08:00
Duplicate of #7

**Closed by skyler-code** 2024-07-20 08:00 UTC
